apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: bookstore-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: "./bookstore"
  prune: true
  sourceRef:
    kind: GitRepository
    name: bookstore-repo
  targetNamespace: default